/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from "./routes/__root";
import { Route as AppImport } from "./routes/_app";
import { Route as AppIndexImport } from "./routes/_app.index";
import { Route as AppTwinsImport } from "./routes/_app.twins";
import { Route as AppSettingsImport } from "./routes/_app.settings";
import { Route as AppPatientsImport } from "./routes/_app.patients";
import { Route as AppModelsImport } from "./routes/_app.models";
import { Route as AppAnalyticsImport } from "./routes/_app.analytics";
import { Route as AppAlertsImport } from "./routes/_app.alerts";
import { Route as AppPatientsPatientIdImport } from "./routes/_app.patients.$patientId";

// Create/Update Routes

const AppRoute = AppImport.update({
  id: "/_app",
  getParentRoute: () => rootRoute,
} as any);

const AppIndexRoute = AppIndexImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => AppRoute,
} as any);

const AppTwinsRoute = AppTwinsImport.update({
  id: "/twins",
  path: "/twins",
  getParentRoute: () => AppRoute,
} as any);

const AppSettingsRoute = AppSettingsImport.update({
  id: "/settings",
  path: "/settings",
  getParentRoute: () => AppRoute,
} as any);

const AppPatientsRoute = AppPatientsImport.update({
  id: "/patients",
  path: "/patients",
  getParentRoute: () => AppRoute,
} as any);

const AppModelsRoute = AppModelsImport.update({
  id: "/models",
  path: "/models",
  getParentRoute: () => AppRoute,
} as any);

const AppAnalyticsRoute = AppAnalyticsImport.update({
  id: "/analytics",
  path: "/analytics",
  getParentRoute: () => AppRoute,
} as any);

const AppAlertsRoute = AppAlertsImport.update({
  id: "/alerts",
  path: "/alerts",
  getParentRoute: () => AppRoute,
} as any);

const AppPatientsPatientIdRoute = AppPatientsPatientIdImport.update({
  id: "/$patientId",
  path: "/$patientId",
  getParentRoute: () => AppPatientsRoute,
} as any);

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/_app": {
      id: "/_app";
      path: "";
      fullPath: "";
      preLoaderRoute: typeof AppImport;
      parentRoute: typeof rootRoute;
    };
    "/_app/alerts": {
      id: "/_app/alerts";
      path: "/alerts";
      fullPath: "/alerts";
      preLoaderRoute: typeof AppAlertsImport;
      parentRoute: typeof AppImport;
    };
    "/_app/analytics": {
      id: "/_app/analytics";
      path: "/analytics";
      fullPath: "/analytics";
      preLoaderRoute: typeof AppAnalyticsImport;
      parentRoute: typeof AppImport;
    };
    "/_app/models": {
      id: "/_app/models";
      path: "/models";
      fullPath: "/models";
      preLoaderRoute: typeof AppModelsImport;
      parentRoute: typeof AppImport;
    };
    "/_app/patients": {
      id: "/_app/patients";
      path: "/patients";
      fullPath: "/patients";
      preLoaderRoute: typeof AppPatientsImport;
      parentRoute: typeof AppImport;
    };
    "/_app/settings": {
      id: "/_app/settings";
      path: "/settings";
      fullPath: "/settings";
      preLoaderRoute: typeof AppSettingsImport;
      parentRoute: typeof AppImport;
    };
    "/_app/twins": {
      id: "/_app/twins";
      path: "/twins";
      fullPath: "/twins";
      preLoaderRoute: typeof AppTwinsImport;
      parentRoute: typeof AppImport;
    };
    "/_app/": {
      id: "/_app/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof AppIndexImport;
      parentRoute: typeof AppImport;
    };
    "/_app/patients/$patientId": {
      id: "/_app/patients/$patientId";
      path: "/$patientId";
      fullPath: "/patients/$patientId";
      preLoaderRoute: typeof AppPatientsPatientIdImport;
      parentRoute: typeof AppPatientsImport;
    };
  }
}

// Create and export the route tree

interface AppPatientsRouteChildren {
  AppPatientsPatientIdRoute: typeof AppPatientsPatientIdRoute;
}

const AppPatientsRouteChildren: AppPatientsRouteChildren = {
  AppPatientsPatientIdRoute: AppPatientsPatientIdRoute,
};

const AppPatientsRouteWithChildren = AppPatientsRoute._addFileChildren(
  AppPatientsRouteChildren,
);

interface AppRouteChildren {
  AppAlertsRoute: typeof AppAlertsRoute;
  AppAnalyticsRoute: typeof AppAnalyticsRoute;
  AppModelsRoute: typeof AppModelsRoute;
  AppPatientsRoute: typeof AppPatientsRouteWithChildren;
  AppSettingsRoute: typeof AppSettingsRoute;
  AppTwinsRoute: typeof AppTwinsRoute;
  AppIndexRoute: typeof AppIndexRoute;
}

const AppRouteChildren: AppRouteChildren = {
  AppAlertsRoute: AppAlertsRoute,
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppModelsRoute: AppModelsRoute,
  AppPatientsRoute: AppPatientsRouteWithChildren,
  AppSettingsRoute: AppSettingsRoute,
  AppTwinsRoute: AppTwinsRoute,
  AppIndexRoute: AppIndexRoute,
};

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren);

export interface FileRoutesByFullPath {
  "": typeof AppRouteWithChildren;
  "/alerts": typeof AppAlertsRoute;
  "/analytics": typeof AppAnalyticsRoute;
  "/models": typeof AppModelsRoute;
  "/patients": typeof AppPatientsRouteWithChildren;
  "/settings": typeof AppSettingsRoute;
  "/twins": typeof AppTwinsRoute;
  "/": typeof AppIndexRoute;
  "/patients/$patientId": typeof AppPatientsPatientIdRoute;
}

export interface FileRoutesByTo {
  "/alerts": typeof AppAlertsRoute;
  "/analytics": typeof AppAnalyticsRoute;
  "/models": typeof AppModelsRoute;
  "/patients": typeof AppPatientsRouteWithChildren;
  "/settings": typeof AppSettingsRoute;
  "/twins": typeof AppTwinsRoute;
  "/": typeof AppIndexRoute;
  "/patients/$patientId": typeof AppPatientsPatientIdRoute;
}

export interface FileRoutesById {
  __root__: typeof rootRoute;
  "/_app": typeof AppRouteWithChildren;
  "/_app/alerts": typeof AppAlertsRoute;
  "/_app/analytics": typeof AppAnalyticsRoute;
  "/_app/models": typeof AppModelsRoute;
  "/_app/patients": typeof AppPatientsRouteWithChildren;
  "/_app/settings": typeof AppSettingsRoute;
  "/_app/twins": typeof AppTwinsRoute;
  "/_app/": typeof AppIndexRoute;
  "/_app/patients/$patientId": typeof AppPatientsPatientIdRoute;
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | ""
    | "/alerts"
    | "/analytics"
    | "/models"
    | "/patients"
    | "/settings"
    | "/twins"
    | "/"
    | "/patients/$patientId";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/alerts"
    | "/analytics"
    | "/models"
    | "/patients"
    | "/settings"
    | "/twins"
    | "/"
    | "/patients/$patientId";
  id:
    | "__root__"
    | "/_app"
    | "/_app/alerts"
    | "/_app/analytics"
    | "/_app/models"
    | "/_app/patients"
    | "/_app/settings"
    | "/_app/twins"
    | "/_app/"
    | "/_app/patients/$patientId";
  fileRoutesById: FileRoutesById;
}

export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren;
}

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
};

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_app"
      ]
    },
    "/_app": {
      "filePath": "_app.tsx",
      "children": [
        "/_app/alerts",
        "/_app/analytics",
        "/_app/models",
        "/_app/patients",
        "/_app/settings",
        "/_app/twins",
        "/_app/"
      ]
    },
    "/_app/alerts": {
      "filePath": "_app.alerts.tsx",
      "parent": "/_app"
    },
    "/_app/analytics": {
      "filePath": "_app.analytics.tsx",
      "parent": "/_app"
    },
    "/_app/models": {
      "filePath": "_app.models.tsx",
      "parent": "/_app"
    },
    "/_app/patients": {
      "filePath": "_app.patients.tsx",
      "parent": "/_app",
      "children": [
        "/_app/patients/$patientId"
      ]
    },
    "/_app/settings": {
      "filePath": "_app.settings.tsx",
      "parent": "/_app"
    },
    "/_app/twins": {
      "filePath": "_app.twins.tsx",
      "parent": "/_app"
    },
    "/_app/": {
      "filePath": "_app.index.tsx",
      "parent": "/_app"
    },
    "/_app/patients/$patientId": {
      "filePath": "_app.patients.$patientId.tsx",
      "parent": "/_app/patients"
    }
  }
}
ROUTE_MANIFEST_END */
